In [1]:
# Random numbers:
# (1) numpy.random.rand():
import numpy as np
print(np.random.rand(2, 3))  # 2x3 array of random numbers (generates values b/w 0 and 1)

[[0.35949087 0.72037563 0.56169421]
 [0.98537374 0.74626787 0.61446139]]


In [2]:
# (2) numpy.random.randn():
print(np.random.randn(3, 2))  # 3x2 array of random samples (99% of values lies b/w -3 and +3).

[[-1.8153287  -0.59413014]
 [ 0.25417088  1.04970435]
 [-2.14218354  0.49358011]]


In [8]:
# (3) numpy.random.normal():
print(np.random.normal(10, 3, (2, 3))) # (values = 10+-3,ie mean=10,std=3)

[[12.75404456  7.26071102  4.51882633]
 [ 8.73483369 12.44579907 13.02705677]]


In [6]:
# (4) numpy.random.randint():
print(np.random.randint(0, 10, size=(2, 2)))  # 2x2 matrix of integers from 0 to 9

[[2 6]
 [5 7]]


In [38]:
my_list=[np.random.randint(20) for i in range (1,10)]
print(my_list)

[5, 11, 15, 9, 16, 9, 10, 14, 10]


In [7]:
# numpy.linspace():
my_arr=np.linspace(0,1,5)
print(my_arr)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
my_arr=np.linspace(11,44,9)
print(my_arr)

[11.    15.125 19.25  23.375 27.5   31.625 35.75  39.875 44.   ]


In [4]:
# numpy.arange():
x = np.arange(1, 11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# numpy.arange():
x = np.arange(5, 87,5)
print(x)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]


In [12]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [1]:
# Array creation:
import numpy as np
my_arr=np.array([1,2,3,4,5])
print(my_arr)

[1 2 3 4 5]


In [2]:
# Updating:
my_arr[1]=100
print(my_arr)

[  1 100   3   4   5]


In [3]:
print(len(my_arr))

5


In [4]:
print(type(my_arr))

<class 'numpy.ndarray'>


In [5]:
#  numpy.zeros():
my_arr=np.zeros((3,4))
print(my_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#  numpy.ones():
my_arr=np.ones((3,4))
print(my_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# Array manipultion:
# (a) numpy.reshape():
my_arr=np.array([1,2,3,4,5,6])
new_arr=my_arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [17]:
my_arr=np.arange(1,21)
new_arr=my_arr.reshape(5,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [18]:
# numpy.ravel():
my_arr=np.array([[2,5],[10,20]])
print(my_arr.ravel())

[ 2  5 10 20]


In [20]:
my_arr=np.array([[2,5],[10,20]])
print(my_arr)

[[ 2  5]
 [10 20]]


In [19]:
# transpose():
my_arr=np.array([[2,5],[10,20]])
trans=my_arr.T
print(trans)

[[ 2 10]
 [ 5 20]]


In [21]:
# concatenate():
ar1=np.arange(1,10)
ar2=np.arange(2,20)
ar1_ar2=np.concatenate((ar1,ar2))
print(ar1_ar2)

[ 1  2  3  4  5  6  7  8  9  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
 17 18 19]


In [22]:
# Mathematical operation:
# (1) mean():
my_arr=np.array([1,2,3,4,5,6])
print(np.mean(my_arr))

3.5


In [23]:
# (2) median():
my_arr=np.array([1,2,3,4,5,6])
print(np.median(my_arr))

3.5


In [25]:
# (3) sum():
my_arr=np.array([1,2,3,4,5,6])
res=np.sum(my_arr)
print(res)

21


In [26]:
# (4) product():
my_arr=np.array([1,2,3,4,5,6])
res=np.prod(my_arr)
print(res)

720


In [27]:
# (5) std():
my_arr=np.array([1,2,3,4,5,6])
res=np.std(my_arr)
print(res)

1.707825127659933


In [29]:
# Indexing and Filtering:
# (1) numpy.where():
my_arr=np.array([1,2,3,4,5,6])
res=np.where(my_arr>2)
print(res)

(array([2, 3, 4, 5]),)


In [31]:
# (2) numpy.argmin():
my_arr=np.array([100,20,30,40,50,60,23,12,27])
res=np.argmin(my_arr)
print(res)

7


In [33]:
# (3) numpy.argmax():
my_arr=np.array([100,20,30,400,50,60,23,12,27])
res=np.argmax(my_arr)
print(res)

3


In [34]:
# Statistical analysis :
#(1) numpy.percentile():
my_arr=np.array([100,20,30,400,50,60,23,12,27])
res=np.percentile(my_arr,50)
print(res)

30.0


In [35]:
# (2) corrcoef():
ad_spend=np.array([10,20])
sales_spend=np.array([5,3])
co_rel=np.corrcoef(ad_spend,sales_spend)
print(co_rel)

[[ 1. -1.]
 [-1.  1.]]
